# Generated by Django 3.0.2 on 2020-11-28 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, verbose_name='Имя пользоватиля')),
                ('email', models.EmailField(max_length=50)),
                ('comment', models.TextField(max_length=2000, verbose_name='Комментарий пользователя')),
                ('videourl', models.CharField(blank=True, max_length=400, null=True, verbose_name='Ссылка на видео с ютуба')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Дата публикации')),
                ('published', models.BooleanField(default=False, verbose_name='Опубликовать комментарий')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='reviews.Reviews', verbose_name='Ответ на отзыв')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.ProductCart', verbose_name='продукт на который написан отзыв')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.CreateModel(
            name='ReviewsImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, upload_to='reviews')),
                ('review', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='reviews.Reviews', verbose_name='Вложенные фотографии')),
            ],
        ),
    ]
